/*
 * Original Copyright (c) 2017, Howard Hughes Medical Institute
 * Licensed under Janelia Research Campus Software License 1.2
 * See license_details/LICENSE-JANELIA.txt
 *
 * Modifications Copyright (c) 2025, Stochastic Analytics, LLC
 * Modifications licensed under MPL 2.0 for academic use; 
 * commercial license required for commercial use.
 * See LICENSE.md for details.
 */

#ifndef __ErrorDialog__
#define __ErrorDialog__

/**
@file
Subclass of ErrorDialog, which is generated by wxFormBuilder.
*/

//// end generated include

/** Implementing ErrorDialog */
class MyErrorDialog : public ErrorDialog {
  public:
    /** Constructor */
    MyErrorDialog(wxWindow* parent);
    //// end generated class members

    void OnClickOK(wxCommandEvent& event);
};

#endif // __ErrorDialog__
