/*
 * Original Copyright (c) 2017, Howard Hughes Medical Institute
 * Licensed under Janelia Research Campus Software License 1.2
 * See license_details/LICENSE-JANELIA.txt
 *
 * Modifications Copyright (c) 2025, Stochastic Analytics, LLC
 * Modifications licensed under MPL 2.0 for academic use; 
 * commercial license required for commercial use.
 * See LICENSE.md for details.
 */

#ifndef __MyNewProjectWizard__
#define __MyNewProjectWizard__

/**
@file
Subclass of NewProjectWizard, which is generated by wxFormBuilder.
*/

#include "ProjectX_gui.h"

//// end generated include

/** Implementing NewProjectWizard */
class MyNewProjectWizard : public NewProjectWizard {
  protected:
    // Handlers for NewProjectWizard events.
    void OnBrowseButtonClick(wxCommandEvent& event);

  public:
    /** Constructor */
    MyNewProjectWizard(wxWindow* parent);
    //// end generated class members

    void OnProjectTextChange(wxCommandEvent& event);
    void OnProjectPathChange(wxCommandEvent& event);
    void OnParentDirChange(wxCommandEvent& event);
    void OnFinished(wxWizardEvent& event);
    void GenerateProjectPath( );
    void CheckProjectPath( );
};

#endif // __MyNewProjectWizard__
