#!/usr/bin/env python3
"""
Format and stage C++/CUDA files using clang-format.

This script mirrors the pre-commit hook logic but automatically formats
and stages files, making it suitable for one-shot invocations without
consuming LLM context.
"""

import subprocess
import sys
from pathlib import Path
from typing import List, Optional


def find_project_root() -> Optional[Path]:
    """Find the git project root."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True
        )
        return Path(result.stdout.strip())
    except subprocess.CalledProcessError:
        return None


def check_clang_format() -> bool:
    """Check if clang-format-14 is available."""
    try:
        subprocess.run(
            ["clang-format-14", "--version"],
            capture_output=True,
            check=True
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def should_exclude_file(file_path: str) -> bool:
    """
    Check if file should be excluded from formatting.

    Args:
        file_path: Relative path to file from project root

    Returns:
        True if file should be excluded, False otherwise
    """
    # Exclude third-party headers
    if file_path.startswith("include/"):
        return True

    # Exclude wxFormBuilder input files
    if file_path.startswith("src/gui/wxformbuilder/"):
        return True

    # Exclude generated wxFormBuilder files by name pattern
    if "ProjectX_gui" in file_path:
        return True

    # Check file header for wxFormBuilder warning
    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            header = ''.join(f.readline() for _ in range(10))
            if any(marker in header for marker in [
                "PLEASE DO *NOT* EDIT THIS FILE",
                "DO NOT EDIT THIS FILE",
                "Generated by wxFormBuilder"
            ]):
                return True
    except (IOError, UnicodeDecodeError):
        pass

    return False


def get_staged_cpp_files() -> List[str]:
    """Get list of staged C++/CUDA files."""
    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
            capture_output=True,
            text=True,
            check=True
        )

        extensions = ('.cpp', '.h', '.cc', '.cxx', '.hpp', '.cu', '.cuh')
        files = [
            line.strip()
            for line in result.stdout.splitlines()
            if line.strip().endswith(extensions)
        ]
        return files
    except subprocess.CalledProcessError:
        return []


def format_file(file_path: Path) -> bool:
    """
    Format a file in-place using clang-format-14.

    Args:
        file_path: Path to file to format

    Returns:
        True if formatting succeeded, False otherwise
    """
    try:
        subprocess.run(
            ["clang-format-14", "-i", str(file_path)],
            check=True
        )
        return True
    except subprocess.CalledProcessError:
        return False


def stage_file(file_path: Path) -> bool:
    """
    Stage a file with git add.

    Args:
        file_path: Path to file to stage

    Returns:
        True if staging succeeded, False otherwise
    """
    try:
        subprocess.run(
            ["git", "add", str(file_path)],
            check=True
        )
        return True
    except subprocess.CalledProcessError:
        return False


def main() -> int:
    """Main entry point."""
    # Find project root
    project_root = find_project_root()
    if not project_root:
        print("Error: Not in a git repository", file=sys.stderr)
        return 1

    # Check for clang-format-14
    if not check_clang_format():
        print("Error: clang-format-14 not found in PATH", file=sys.stderr)
        print("Please install clang-format-14", file=sys.stderr)
        return 1

    # Check for .clang-format config
    clang_format_config = project_root / ".clang-format"
    if not clang_format_config.exists():
        print("Warning: .clang-format not found in project root", file=sys.stderr)
        print("Skipping format", file=sys.stderr)
        return 0

    # Get staged files
    staged_files = get_staged_cpp_files()
    if not staged_files:
        print("No C++/CUDA files staged")
        return 0

    print("Formatting and staging C++/CUDA files...")

    formatted_count = 0
    skipped_count = 0
    error_count = 0

    for file_path_str in staged_files:
        file_path = project_root / file_path_str

        # Skip excluded files
        if should_exclude_file(file_path_str):
            print(f"  Skipping (excluded): {file_path_str}")
            skipped_count += 1
            continue

        # Skip if file doesn't exist
        if not file_path.exists():
            print(f"  Skipping (not found): {file_path_str}")
            skipped_count += 1
            continue

        # Format the file
        if format_file(file_path):
            # Stage the formatted file
            if stage_file(file_path):
                print(f"  Formatted and staged: {file_path_str}")
                formatted_count += 1
            else:
                print(f"  Error staging: {file_path_str}", file=sys.stderr)
                error_count += 1
        else:
            print(f"  Error formatting: {file_path_str}", file=sys.stderr)
            error_count += 1

    # Summary
    print()
    print(f"Summary: {formatted_count} formatted, {skipped_count} skipped, {error_count} errors")

    if error_count > 0:
        return 1

    print("All files formatted and staged successfully")
    return 0


if __name__ == "__main__":
    sys.exit(main())
