name: cisTEMx GPU release

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  run_build:
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "GPU release"
      configure_options: "--with-cuda "
      global_configure_options: "--disable-staticmode --enable-openmp --enable-samples --enable-experimental --disable-multiple-global-refinements "
      runs_on_os: self-hosted
      CC: icc
      CXX: icpc
      cppstandard: 17


