name: cisTEMx GPU release

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  run_build:
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "GPU_release"
      configure_options: "--with-cuda "
      global_configure_options: "--disable-staticmode --enable-openmp --enable-experimental --disable-multiple-global-refinements --enable-smooth-mip --disable-multiple-global-refinements --enable-build-resize --enable-build-resample --enable-build-sum_all_mrc_files --enable-build-sum_all_tif_files --enable-build-convert_par_to_star --enable-build-quick_test"
      runs_on_os: self-hosted
      CC: icc
      CXX: icpc
      cppstandard: 17


